IdentitySchool/Controllers/CourseController.cs
using System.Collections.Generic;
using IdentitySchool.Interface;
using IdentitySchool.Models;
using IdentitySchool.ViewModels;
using Microsoft.AspNetCore.Mvc;


namespace IdentitySchool.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly ITeacherService _teacherService;
        private readonly IAssignmentService _assignmentService;
        private readonly IStudentService _studentService;



        public CourseController(ICourseService courseService, ITeacherService teacherService, IAssignmentService assignmentService, IStudentService studentService)
        {
            _courseService = courseService;
            _teacherService = teacherService;
            _assignmentService = assignmentService;
            _studentService = studentService;
        }

        public IActionResult Index()
        {
            return View(_courseService.AllCourse());
        }

        public IActionResult CreateCourse()
        {
            return View();
        }

        public IActionResult CreateAssignment(int courseId)
        {
            var vm = new AssignmentVM
            {
                CourseId = courseId
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCourse([Bind("Title, Description")] Course course)
        {
            if (ModelState.IsValid)
            {
                course = _courseService.CreateCourse(course.Title, course.Description);
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateAssignment(Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                _assignmentService.CreateAssignment(assignment);

                return RedirectToAction(nameof(Details), new { id = assignment.CourseId });
            }
            return View(assignment);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = _courseService.FindCourse((int)id);
            if (course == null)
            {
                return NotFound();
            }
            CourseVM name = new CourseVM
            {
                CourseId = course.CourseId,
                Title = course.Title,
                Description = course.Description,
                Teachers = _teacherService.AllTeacher(),
            };
            return View(name);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CourseVM course)
        {
            if (ModelState.IsValid)
            {
                var teacherF = _teacherService.FindTeacher(course.TeacherId);

                var courseToUpdate = new Course
                {
                    Title = course.Title,
                    Description = course.Description,
                    Teacher = teacherF,
                    CourseId = course.CourseId
                };
                _courseService.UpdateCourse(courseToUpdate);
                return RedirectToAction(nameof(Index));
            }

            CourseViewModel CourseViewModel = new CourseViewModel();           

            return View(course);
        }

        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                _courseService.DeleteCourse((int)id);
                _assignmentService.DeleteAssignment((int)id);
                return RedirectToAction(nameof(Index));
            }
            return Content("");
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = _courseService.FindCourse((int)id);

            if (course == null)
            {
                return NotFound();
            }

            CourseViewModel CourseViewModel = new CourseViewModel();
            CourseViewModel.Course = course;

            CourseViewModel.Assignments = course.Assignments;


            List<Student> studentsNotInCourse = _studentService.AllStudents();

            foreach (var item in course.StudentsCourses)
            {
                studentsNotInCourse.Remove(item.Student);
            }

            CourseViewModel.Students = studentsNotInCourse;

            return View(CourseViewModel);
        }
        public IActionResult AddStudentToCourseSave(int cId, int sId)
        {
            var course = _courseService.FindCourse(cId);
            if (course == null)
            {
                return NotFound();
            }

            var student = _studentService.FindStudent(sId);
            if (student == null)
            {
                return NotFound();
            }

            foreach (var item in course.StudentsCourses)
            {
                if (item.StudentId == sId)
                {
                    return RedirectToAction(nameof(Details), new { id = cId });
                }
            }

            _courseService.AddStudentToCourse(course,student);    

            return RedirectToAction(nameof(Details), new { id = cId });
        }

        public IActionResult RemoveStudentToCourse(int cId, int sId)
        {
            var course = _courseService.FindCourse(cId);
            if (course == null)
            {
                return NotFound();
            }

            _courseService.RemoveStudentToCourse(course, sId);

            return RedirectToAction(nameof(Details), new { id = cId });
        }

        public IActionResult DeleteAssignment(int? id, int courseId)
        {
            if (id != null)
            {
                _assignmentService.DeleteAssignment((int)id);
                return RedirectToAction(nameof(Details), new { id = courseId });
            }
            return Content("");
        }
    }
}

IdentitySchool/Controllers/StudentController.cs
using IdentitySchool.Interface;
using IdentitySchool.Models;
using Microsoft.AspNetCore.Mvc;

namespace IdentitySchool.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _student;

        public StudentController(IStudentService student)
        {
            _student = student;
        }

        public IActionResult Index()
        {
            return View(_student.AllStudents());
        }

        [HttpGet]
        public IActionResult CreateStudent()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStudent([Bind("Name,Phone,Location")]Student student)
        {
            if (ModelState.IsValid)
            {
                student = _student.CreateStudent(student.Name, student.Phone, student.Location);
                return RedirectToAction(nameof(Index));
            }

            return View(student); 
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = _student.FindStudent((int)id);
            if (student == null)
            {
                return NotFound();
            }



            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Student student)
        {

            if (ModelState.IsValid)
            {
                _student.UpdateStudent(student);
                return RedirectToAction(nameof(Index));

            }
            return View(student);
        }
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                _student.DeleteStudent((int)id);
                return RedirectToAction(nameof(Index));
            }
            return Content("");
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = _student.FindStudent((int)id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }
    }
}

IdentitySchool/Controllers/TeacherController.cs
using IdentitySchool.Interface;
using IdentitySchool.Models;
using Microsoft.AspNetCore.Mvc;

namespace IdentitySchool.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherService _teacherService;

        public TeacherController(ITeacherService teacherService)
        {
            _teacherService = teacherService;
        }

        public IActionResult Index()
        {
            return View(_teacherService.AllTeacher());
        }

        [HttpGet]
        public IActionResult CreateTeacher()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateTeacher([Bind("Name,Description")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                teacher = _teacherService.CreateTeacher(teacher.Name, teacher.Description);
                return RedirectToAction(nameof(Index));
            }

            return View(teacher);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var teacher = _teacherService.FindTeacher((int)id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Teacher teacher)
        {

            if (ModelState.IsValid)
            {
                _teacherService.UpdateTeacher(teacher);
                return RedirectToAction(nameof(Index));

            }
            return View(teacher);
        }
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                _teacherService.DeleteTeacher((int)id);
                return RedirectToAction(nameof(Index));
            }
            return Content("");
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var teacher = _teacherService.FindTeacher((int)id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }
    }
}

IdentitySchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>School Al Mouallem</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href="~/css/Style.css" rel="stylesheet" />
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
</head>
<body>
    <header>
        <nav class="nav navbar-collapse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" id="Almouallem">School Al Mouallem IT</a>
                </div>
                <ul class="nav navbar-nav">

                    <li class="nav-item" id="NavBar">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teachers</a>
                    </li>
                    <li class="nav-item" id="NavBar">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                    </li>
                    <li class="nav-item" id="NavBar">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                    </li>
                    <li class="nav-item" id="NavBar">@Html.ActionLink("About", "About", "Home")</li>
                    <li class="nav-item" id="NavBar">@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </nav>        
    </header>
    <div>
        @RenderBody()
    </div>
    <footer id="footerr">
        <p>Abdullah Mouallem &copy; @DateTime.Now.ToString("yyyy")</p>
    </footer>
</body>
</html>

IdentitySchool/Views/Shared/_Partial.cshtml
@using Microsoft.AspNetCore.Http.Features

@{
    var consentFeature = Context.Features.Get<ITrackingConsentFeature>();
    var showBanner = !consentFeature?.CanTrack ?? false;
    var cookieString = consentFeature?.CreateConsentCookie();
}

@if (showBanner)
{
    <div id="cookieConsent" class="alert alert-info alert-dismissible fade show" role="alert">
        Use this space to summarize your privacy and cookie use policy. <a asp-area="" asp-controller="Home" asp-action="Privacy">Learn More</a>.
        <button type="button" class="accept-policy close" data-dismiss="alert" aria-label="Close" data-cookie-string="@cookieString">
            <span aria-hidden="true">Accept</span>
        </button>
    </div>
    <script>
        (function () {
            var button = document.querySelector("#cookieConsent button[data-cookie-string]");
            button.addEventListener("click", function (event) {
                document.cookie = button.dataset.cookieString;
            }, false);
        })();
    </script>
}

IdentitySchool/Views/Shared/_ScriptsPartial.cshtml
<environment include="Development">
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"
            asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator"
            crossorigin="anonymous"
            integrity="sha256-F6h55Qw6sweK+t7SiOJX+2bpSAa3b/fnlrVCJvmEj1A=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
            crossorigin="anonymous"
            integrity="sha256-9GycpJnliUjJDVDqP0UEu/bsm9U+3dnQUH8+3W10vkY=">
    </script>
</environment>